/* Auto-generated by contracts/ts/script.ts (user). Do not edit manually. */
export type Address = string;
export type Bytes = string;

export namespace CaveStateModule {
	export type Cave = {
		cleanliness: bigint;
		security: bigint;
		hygiene: bigint;
		comfort: bigint;
	};
}

export namespace Dino {
	export type DinoData = {
		genesis: Dino.Genesis;
		progress: Dino.Progress;
		status: Dino.Status;
		stats: Dino.Stats;
	};
	export type Genesis = {
		_initialized: boolean;
		name: string;
		speciesId: bigint;
		birthTimestamp: bigint;
	};
	export type Params = {
		name: string;
		speciesId: bigint;
	};
	export type Progress = {
		xp: bigint;
		weight: bigint;
		level: bigint;
	};
	export type Stats = {
		health: bigint;
		force: bigint;
		endurance: bigint;
		agility: bigint;
		intelligence: bigint;
	};
	export type Status = {
		alive: boolean;
		hunger: boolean;
		thirst: boolean;
	};
}

export namespace DinoAccount {
	export type Call = {
		target: Address;
		value: bigint;
		data: Bytes;
	};
}

export namespace DinoFactory {
	export type DinoContext = {
		dinoId: bigint;
		dinoAccount: Address;
		dino: Dino.DinoData;
	};
}

export namespace ItemsSet {
	export enum EffectKind {
		Weight = 0,
		Health = 1,
		ClearHunger = 2,
		ClearThirst = 3,
		SecurityBonus = 4,
		HygieneBonus = 5,
		ComfortBonus = 6,
	}
	export enum ItemRarity {
		Common = 0,
		Uncommon = 1,
		Rare = 2,
		Epic = 3,
		Legendary = 4,
		Mythic = 5,
	}
	export enum ItemType {
		Consumable = 0,
		Habitat = 1,
		Weapon = 2,
		Equipment = 3,
		Quest = 4,
		Resource = 5,
		Artifact = 6,
		Currency = 7,
		Container = 8,
		Key = 9,
		Blueprint = 10,
		Cosmetic = 11,
	}
	export type Effect = {
		kind: ItemsSet.EffectKind;
		magnitude: bigint;
	};
	export type Item = {
		name: string;
		rarity: ItemsSet.ItemRarity;
		itemType: ItemsSet.ItemType;
		trading: ItemsSet.ItemTrading;
		usage: ItemsSet.ItemUsage;
		requirements: ItemsSet.ItemRequirements;
		metadata: ItemsSet.ItemMetadata;
		effects: Array<ItemsSet.Effect>;
	};
	export type ItemMetadata = {
		symbol: string;
		decimals: bigint;
	};
	export type ItemRequirements = {
		requiredLevel: bigint;
	};
	export type ItemTrading = {
		tradable: boolean;
		sellable: boolean;
		price: bigint;
	};
	export type ItemUsage = {
		destroyOnUse: boolean;
		soulbound: boolean;
	};
}

export namespace SpeciesRegistry {
	export type Species = {
		name: string;
		stats: SpeciesRegistry.Stats;
	};
	export type Stats = {
		force: bigint;
		endurance: bigint;
		agility: bigint;
		intelligence: bigint;
	};
}
