/* Auto-generated by contracts/ts/script.ts (user). Do not edit manually. */
export type Address = string;
export type Bytes = string;

export namespace CaveStateModule {
	export type Cave = {
		cleanliness: bigint;
		security: bigint;
		hygiene: bigint;
		comfort: bigint;
	};
}

export namespace DinoAccount {
	export type Call = {
		target: Address;
		value: bigint;
		data: Bytes;
	};
}

export namespace DinoFactory {
	export type Dino = {
		dinoId: bigint;
		dinoAccount: Address;
		dinoGenesis: DinoGenesis.Genesis;
		dinoProfile: DinoProfile.Profile;
	};
}

export namespace DinoGenesis {
	export type Genesis = {
		_initialized: boolean;
		name: string;
		speciesId: bigint;
		birthTimestamp: bigint;
	};
	export type GenesisParams = {
		name: string;
		speciesId: bigint;
	};
}

export namespace DinoProfile {
	export type Profile = {
		alive: boolean;
		health: bigint;
		hunger: boolean;
		thirst: boolean;
		weight: bigint;
		level: bigint;
		xp: bigint;
	};
}

export namespace ItemsSetBase {
	export enum EffectKind {
		Weight = 0,
		Health = 1,
		ClearHunger = 2,
		ClearThirst = 3,
		SecurityBonus = 4,
		HygieneBonus = 5,
		ComfortBonus = 6,
	}
	export enum ItemBaseRarity {
		Common = 0,
		Uncommon = 1,
		Rare = 2,
		Epic = 3,
		Legendary = 4,
		Mythic = 5,
	}
	export enum ItemBaseType {
		Consumable = 0,
		Habitat = 1,
		Weapon = 2,
		Equipment = 3,
		Quest = 4,
		Resource = 5,
		Artifact = 6,
		Currency = 7,
		Container = 8,
		Key = 9,
		Blueprint = 10,
		Cosmetic = 11,
	}
	export type Effect = {
		kind: ItemsSetBase.EffectKind;
		magnitude: bigint;
	};
	export type ItemBase = {
		rarity: ItemsSetBase.ItemBaseRarity;
		itemType: ItemsSetBase.ItemBaseType;
		trading: ItemsSetBase.ItemTrading;
		usage: ItemsSetBase.ItemUsage;
		requirements: ItemsSetBase.ItemRequirements;
		metadata: ItemsSetBase.ItemBaseMetadata;
		effects: Array<ItemsSetBase.Effect>;
	};
	export type ItemBaseMetadata = {
		name: string;
		symbol: string;
		decimals: bigint;
	};
	export type ItemRequirements = {
		requiredLevel: bigint;
	};
	export type ItemTrading = {
		tradable: boolean;
		sellable: boolean;
		price: bigint;
	};
	export type ItemUsage = {
		destroyOnUse: boolean;
		soulbound: boolean;
	};
}

export namespace JobsRegistry {
	export type Job = {
		name: string;
		dailyPay: bigint;
		trainingCost: bigint;
		requiredLevel: bigint;
	};
}

export namespace SpeciesRegistry {
	export type Species = {
		name: string;
		stats: SpeciesRegistry.Stats;
	};
	export type Stats = {
		force: bigint;
		endurance: bigint;
		agility: bigint;
		intelligence: bigint;
	};
}
